name: Continuous Deployment
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SERVER_IP: 195.114.30.143
      SERVER_PORT: 22
      SSH_USERNAME: staging-bot
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SOURCE_DIR: 'dist'
      TARGET_DIR: 'instant-alpha'
    steps:
      - uses: actions/checkout@v1 
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Create folders
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: mkdir -p /var/www/staging.random.studio/${{ env.TARGET_DIR }}
      - name: Deploy preview
        uses: AEnterprise/rsync-deploy@1.0.1
        env:
          ARGS: "-e -c -r --delete"
          DEPLOY_KEY: ${{ env.SSH_KEY }}
          USERNAME: ${{ env.SSH_USERNAME }}
          FOLDER: "./${{ env.SOURCE_DIR }}/"
          SERVER_DESTINATION: '/var/www/staging.random.studio/${{ env.TARGET_DIR }}/'
